### PR TITLE
Enable cython coverage

### PR DESCRIPTION
**Pull request by asvetlov**

### CODE REVIEW

**Comment by AraHaan** [comment]
@asvetlov mind somehow adding multidict and yarl wheels for Python 3.6 for windows and linux? Because pip cannot successfully build them for me therefore breaking the latest aiohttp.

**Comment by AraHaan** [comment]
@asvetlov if and when my changes to .travis.yml is merged you might end up having to rebase this PR.

**Comment by asvetlov** [comment]
As I see current Cython still have false negatives for coverage report.
Will merge after Cython guys will fix their bug.

**Comment by AraHaan** [comment]
ok, also mind reviewing my yarl PR?

**Comment by asvetlov** [comment]
Done

**Comment by asvetlov** [comment]
Cython has gone

**Pull request closed without merging**
