### PR TITLE
Removed LICENSE filename extension @ MANIFEST.in file

### PR DESCRIPTION
**Pull request by ccarrizosa**
Hello,
LICENSE file is not included correctly at MANIFEST.in file. I've removed the left over ".txt" extension. 

Thanks.
Carlos Carrizosa

### CODE REVIEW

**Comment by asvetlov** [comment]
Thanks!

**Comment by urnenfeld** [comment]
Hello,

When do you plan a release containing this fix?
It creates a license checking problem with the yocto recipes we are developing.
Depending on this we fetch the sources from one location or another.
Thanks accepting the pull!

**Comment by asvetlov** [comment]
Done.
Please wait a bit for build bot finishing.

**Comment by urnenfeld** [comment]
Of course, the intention was only to know your plan.
Thanks

**Comment by ccarrizosa** [comment]
Thanks for this release! 
We needed to create a bitbake recipe for your package and it was not possible without the LICENSE file. 
Just in case you're interested, you'll find it [here](https://github.com/ccarrizosa/meta-widde/blob/master/recipes-devtools/python/python3-multidict_2.1.4.bb)

**Comment by asvetlov** [comment]
Sure, but what is `bitbake recipe`?

**Comment by urnenfeld** [comment]
Hello, everything comes from: https://www.yoctoproject.org/

Summarizing a recipe is the input to the yocto/bitbake/poky ecosystem to be able to deploy a package into a Linux Embedded system.

So in this particular case, these small files(*.bb recipes) allow the build system to deploy some of your packages, preinstalled in a Linux Embedded final image.

**Comment by asvetlov** [comment]
Thank you for information

**Pull request merged**
