### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by hugovk**
## What do these changes do?

The [Python 3.12 release candidate is out!](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

## Are there changes in behavior for the user?

No.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by hugovk** [comment]
This will fail with a segmentation fault (https://github.com/hugovk/multidict/actions/runs/6028022143), already reported at https://github.com/aio-libs/multidict/issues/862.

And it will be fixed by https://github.com/aio-libs/multidict/pull/864.

To demonstrate, here's a branch (https://github.com/hugovk/multidict/tree/add-3.12b) with both this PR and that PR's commits which passes (https://github.com/hugovk/multidict/actions/runs/6029781394).

**Comment by h-vetinari** [comment]
Compiling 6.0.4 + #864 with clang >=15 errors due to using `NULL` (which has type `void *`) to initialize an integer.
```
  multidict/_multidict.c:458:37: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
      static _PyArg_Parser _parser = {NULL, _keywords, "getall", 0};
                                      ^~~~
  /Users/runner/miniforge3/conda-bld/multidict_1696714043821/_build_env/lib/clang/15.0.7/include/stddef.h:89:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
```

**Comment by guidopetri** [comment]
@asvetlov @webknjaz any ETA on this being merged in + released?

**Comment by davepeck** [comment]
@h-vetinari 

> Compiling 6.0.4 + #864 with clang >=15 errors due to using `NULL` (which has type `void *`) to initialize an integer.

I run into this too on my Mac with `clang` version `17.0.4` and when using python 3.12.

Since _so many_ packages transitively depend on `multidict` under the hood (`openai` and `litestar`, to name just two examples), I've taken to temporarily invoking `pip install` with:

```
CFLAGS="-Wno-error=int-conversion" pip install ...
```

It ain't pretty, but it does work.

**Comment by robd003** [comment]
@asvetlov can we get some 👀 on this?

Python 3.12 has been available for over 2 months now

**Pull request merged**
