### PR TITLE
Rewrite benchmarks using perf

### PR DESCRIPTION
**Pull request by gagoman**
Good day.

I've rewritten benchmarks using [perf](https://github.com/haypo/perf) module.
I've found it easier to have a quick way to add another `MultiDict` impl to benchmark suite.
It would allow to run benchmarks against specific implementation and use all perf features (not to mention `compare_to`). E.g.:

```
python benchmarks/benchmark.py --impl multidict_cython -o multidict_python.py36.json
python benchmarks/benchmark.py --impl multidict_cython_rewrite -o multidict_python_rewrite.py36.json
python -m perf compare_to --table multidict_python.py36.json multidict_python_rewrite.py36.json
```

Feel free to share your opinion.

### CODE REVIEW

**Comment by asvetlov** [comment]
I like the idea.
Let me review the PR later.

**Comment by gagoman** [comment]
Sure, will do

**Comment by gagoman** [comment]
@asvetlov I've finally written something. Please take a look if docs are more or less clear.

Also, could you please share your opinion on `timeit` (e.g. https://github.com/aio-libs/multidict/pull/179/files#diff-98d75135e82833a7e0a1181647f5063fR129) vs `bench_time_func` (e.g. https://github.com/aio-libs/multidict/pull/179/files#diff-b7e1078858cccebfaca5e6143ebacc2aR66) style. Should I rewrite benchmarks in `istr.py` to also be `timeit`?

**Comment by gagoman** [comment]
@asvetlov should I do something else here?

**Comment by asvetlov** [comment]
I think everything is done.
We should choose between `timeit` and `bench_time_func`.
Honestly I have no preferention

**Comment by asvetlov** [comment]
I have no preferences -- please choose what you want.

**Comment by gagoman** [comment]
@asvetlov done

**Comment by asvetlov** [comment]
Cool! Thanks!

**Pull request merged**
