### PR TITLE
Fix segfault import when multidict bundled with pyinstaller.

### PR DESCRIPTION
**Pull request by iemelyanov**
## What do these changes do?

Fix segfault import when multidict bundled with pyinstaller.

## Are there changes in behavior for the user?

No

## Related issue number

https://github.com/aio-libs/multidict/issues/432

## Checklist

- [X] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by asvetlov** [comment]
Sorry, I don't understand how it fixes the project.
Why did it fail before?

**Comment by iemelyanov** [comment]
> Sorry, I don't understand how it fixes the project.
> Why did it fail before?

Mb better split this fix on two.

1. Fix segfault which happened when failed get attribute https://github.com/aio-libs/multidict/blob/master/multidict/_multidict.c#L1494 by deleting `decrefs` of static objects.
2. Fix incorrect get attribute.

One interesting thing is that `multidict` correct imported and work event if internally happened `fail` and a big part of code in `PyInit__multidict` not executed!

**Comment by asvetlov** [comment]
Things that bother me:
1. `_mdrepr` is imported from `multidict._multidict_base` on the current master, why additional import in `__init__.py` is needed?
2. If the import of `multidict._multidict` module fails `PyInit__multidict` returns `NULL`, the module object is even not created. Why `pyinstaller` things that the import was succeded. I expect some kind of `ImportError` exception raising.

In conclusion, `pyinstaller`'s import machinery looks buggy at least partially. 
I would know what part is broken. For now, the fix looks like making really very weird things to slip between pyinstaller bugs.
Please correct me if I'm wrong.

**Comment by iemelyanov** [comment]
> Things that bother me:
> 
> 1. `_mdrepr` is imported from `multidict._multidict_base` on the current master, why additional import in `__init__.py` is needed?
> 2. If the import of `multidict._multidict` module fails `PyInit__multidict` returns `NULL`, the module object is even not created. Why `pyinstaller` things that the import was succeded. I expect some kind of `ImportError` exception raising.
> 
> In conclusion, `pyinstaller`'s import machinery looks buggy at least partially.
> I would know what part is broken. For now, the fix looks like making really very weird things to slip between pyinstaller bugs.
> Please correct me if I'm wrong.

You right. For me, this `fails` looks strange too and mb we should more deeply investigate this issue.

**Comment by iemelyanov** [comment]
I propose to close this PR and live #433 open until we don't understand what's going on in `pyinstaller` and why `import multidict` work event if `fail` happen here - https://github.com/aio-libs/multidict/blob/master/multidict/_multidict.c#L1494. What do you think?

**Comment by asvetlov** [comment]
Agree

**Pull request closed without merging**
