### PR TITLE
Fix gc track for iterator and pair_list.

### LINKED ISSUE #320: Call PyObject_GC_Track() for views and iterators after creation
Calls like `PyObject_GC_New` doesn't track returned objects, an explicit `PyObject_GC_Track` call is needed IIRC

/cc @iemelyanov

### PR DESCRIPTION
**Pull request by iemelyanov**
Resolve #320 

Only iterators and pair_list contains this bug.

### CODE REVIEW

**Comment by asvetlov** [comment]
I think views should be tracked as well

**Comment by iemelyanov** [comment]
> I think views should be tracked as well

Mb I am missing something but all objects created by gc_new in views don't have this problem.

**Comment by asvetlov** [comment]
LGTM, please merge

**Comment by iemelyanov** [comment]
> LGTM, please merge

What I should use for merge - "Squash and merge" or "Rebase and merge"? :)

**Comment by asvetlov** [comment]
Squash.
Please re-read the squashed commit message. 
If it is too long or contains non-valuable lines like `Fixed tests` etc -- edit the message before committing.

**Comment by iemelyanov** [comment]
> Squash.
> Please re-read the squashed commit message.
> If it is too long or contains non-valuable lines like `Fixed tests` etc -- edit the message before committing.

Ok. I understand. Thank you.

**Pull request merged**
