### PR TITLE
Upgrade README badges to be more informative

### PR DESCRIPTION
**Pull request by webknjaz**
Ref #4

### CODE REVIEW

**Comment by webknjaz** [comment]
@asvetlov plz check failing RTD status

**Comment by asvetlov** [comment]
Fixed. Thanks for pointing out.

**Comment by webknjaz** [comment]
Badge is still red

**Comment by asvetlov** [comment]
Maybe you see cached version?
On my laptop I have green "docs: passed" badge

**Comment by webknjaz** [comment]
It's cached by github:
https://camo.githubusercontent.com/0bb63dfe3b824ee9cece79a0121f95b92d2b9170/68747470733a2f2f72656164746865646f63732e6f72672f70726f6a656374732f6d756c7469646963742f62616467652f3f76657273696f6e3d6c6174657374

**Comment by webknjaz** [comment]
Original one is green, you are right: https://readthedocs.org/projects/multidict/badge/?version=latest

**Pull request merged**
