### PR TITLE
leakfix

### PR DESCRIPTION
**Pull request by thehesiod**
fix from @gpfei

resolves issue: https://github.com/aio-libs/multidict/issues/105

### CODE REVIEW

**Comment by asvetlov** [comment]
LGTM.
Do you want to write a test?
Making reliable test for this case is hard: the problem is not missing DECREF, collecting memory info from the whole process might vary.

**Comment by thehesiod** [comment]
added test, seems to work

**Comment by asvetlov** [comment]
multidict 3.1.1 released

Thanks for contribution

**Comment by thehesiod** [comment]
thanks to @gpfei ! I was racking my brain trying to figure out what was wrong :)

**Pull request merged**
