### PR TITLE
Enable OS X builds in Travis CI

### PR DESCRIPTION
**Pull request by webknjaz**
* Implemented at their own stage
* Triggered for cron builds, tagged builds or API calls (manually triggered via Travis CI web-interface)

### CODE REVIEW

**Comment by webknjaz** [comment]
Test build, triggered manually: https://travis-ci.org/aio-libs/multidict/builds/282416835

**Comment by asvetlov** [comment]
Perfect! Thanks!

**Comment by asvetlov** [comment]
Is it possible to setup autodeployment of MacOSX binary wheels on travis?

**Comment by webknjaz** [comment]
Sure, it's as easy

**Pull request merged**
