### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by asvetlov**

### CODE REVIEW

**Comment by decaz** [comment]
@asvetlov I'm afraid that the bug is not fixed, - still experiencing memory leak problems.

**Comment by asvetlov** [comment]
Well, it fixes aiohttp server at least.
Thanks for letting me know.

**Comment by pauleikis** [comment]
I can confirm that this does not fix aiohttp client

**Comment by Olegt0rr** [comment]
Please fix memory leak
```
#1: aiohttp/client_reqrep.py:300: 40187.8 KiB
self.headers = CIMultiDict()
```

**Pull request merged**
